<a href="https://colab.research.google.com/github/shriyaD13/ANN_Churn_Modelling/blob/main/ANN_Churning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artifical neural network

### Importing libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.5.0'

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [5]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Labeling gender coloumn

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [8]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One hot coding for location coloumn

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = "passthrough")
x = np.array(ct.fit_transform(x))

In [10]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Train-test split

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2,random_state = 0)

Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Building ANN

### Initializing ANN

In [13]:
ann = tf.keras.models.Sequential()

### Adding the input and first hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units= 6, activation='relu'))

### Adding Second Hidden Layer

In [15]:
ann.add(tf.keras.layers.Dense(units= 6, activation='relu'))

### Adding output layer

In [16]:
ann.add(tf.keras.layers.Dense(units= 1, activation='sigmoid'))

# Training the ANN

### Compiling the ANN

In [17]:
# for binary classification- loss = binary_crossentropy
# for other clasification - loss = categorical_crossentropy
ann.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

### Training the ANN

In [19]:
ann.fit(X_train,y_train,batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.4971 - accuracy: 0.7726
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4472 - accuracy: 0.8005
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4352 - accuracy: 0.8049
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4287 - accuracy: 0.8059
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4219 - accuracy: 0.8092
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4148 - accuracy: 0.8121
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4071 - accuracy: 0.8163
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3992 - accuracy: 0.8184
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3913 - accuracy: 0.8221
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3842 - accura

# Making the predictions and evaluating the model

### Predicting

In [24]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

[[False]]


predicting the test set result

In [28]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the confusion matrix

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1485  110]
 [ 253  152]]


0.8185